#!/usr/bin/env bash

to_echo() {
    if [ "$1" -eq 1 ]; then
        echo "$2"
    fi
}

read_tool_versions_write_to_env() {
    local -r tool_versions_file="$1"

    # loop over each line of the .tool-versions file
    while read -r line; do
        # split the line into a bash array using the default space delimeter
        IFS=" " read -r -a lineArray <<<"$line"

        # get the key and value from the array, set the key to all uppercase
        key="${lineArray[0],,}"
        value="${lineArray[1]}"

        # ignore comments, comments always start with #
        if [[ ${key:0:1} != "#" ]]; then
            full_key="${key/-/_}_tool_version"
            export "${full_key/-/_}=${value}"
        fi
    done <"$tool_versions_file"
}

read_tool_versions_write_to_env '.tool-versions'

set -x

# shellcheck disable=SC2048
earthly $* \
  --NODE_VERSION=${node_tool_version}
